#!/usr/bin/env bash
#
#  Distribute scripts to active script bin
#
declare PROJECT_DIR=~/bin/s3g-backup
declare BIN_DIR=~/bin

__copy() {
  # move project files into script bin
  local separator='-----------------------'
  local file=''
  local -ra dirs=()
  local -ra files=(
    'janks'
    'janks.conf.sh'
  )

  printf "%s\n" "${separator}"
  for file in "${files[@]}"; do
    cp "${file}" "${BIN_DIR}" \
      && printf "👍🏻  Copied: %s to %s\n" "${file}" "${BIN_DIR}"
  done
  printf "%s\n" "${separator}"
  for dir in "${dirs[@]}"; do
    cp -r "${dir}" "${BIN_DIR}" \
      && printf "👍🏻  Copied: %s to %s\n" "${dir}" "${BIN_DIR}"
  done
  printf "%s\n" "${separator}"

}

__control() {
  ssh control mkdir -p /home/ubuntu/bin/
  scp -r ~/bin/xs-janks/* control:/home/ubuntu/bin/
}

#
# Flags are for extensibility,
#  * currently all comibnations result in copy, except (help, --help)
#
declare FLAG=${1:-help}
case ${FLAG} in
  --copy|copy) __copy; exit 0; ;;
  --all|all) __copy; exit 0;  ;;
  --control|ctrl) __control; exit 0; ;;
  --help|help)
    echo '
    Usage
      ./dist --help
      ./dist --copy
      ./dist --all
    '
    exit 0
    ;;
    *) __copy; exit 0; ;;
esac
