#!/usr/bin/env bash
# ================================================================
# -*- mode: bash -*-
# vi: set ft=sh
# ****************************************************************
#
# DESCRIPTION
#   Jenkins helper script
#    * start jenkins from war file
#    * backup and restore Jenkins
#
# SYNTAX & EXAMPLES
#    See 'SYNTAX' (below)
#
# ----------------------------------------------------------------
# IMPLEMENTATION
#    version         script 0.0.4
#    author          Greg Milligan
#    copyright       Copyright (c) 2017 http://www.xybersolve.com
#    license         GNU General Public License
#
# ================================================================
#  DEBUG OPTION
#    set -n  # Uncomment to check your syntax, without execution.
#    set -x  # Uncomment to debug this shell script
#
# ---------------------------------------------------------------
#
# TODO:
# ****************************************************************


# ---------------------------------------
# CONFIGFURATION
# ---------------------------------------
# strict environment
set -o errexit  # exit on command error status
set -o nounset  # no unreadonlyd variables
set -o pipefail # failr on pipe failures
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: ${?}" >&2' ERR

# ---------------------------------------
# GLOBAL VARIABLES
# ---------------------------------------
# booleans
declare -ir TRUE=1
declare -ir FALSE=0
# script info

declare -r PROGNAME="$(basename ${0})"
declare -r VERSION=0.0.1
declare -r SUBJECT=""
declare -r KEYS=""
declare -ri MIN_ARG_COUNT=1
declare -r SYNTAX=$(cat <<EOF

    Script: ${PROGNAME}
    Purpose:
    Usage: ${PROGNAME} [-h|--help] [-v|--version]

    Options:
      --help:  help and usage
      --start: Start Jenkins using war file

      Jenkins from WAR:
      --ver: Version of Jenkins to start
      --versions: View local war versions
      --home=<jenkins home direcotry>: Directory to backup/restore, default: ~/.jenkins
      --file=<archive filename>: Archive filename (no path information required)
      --latest: Get the latest jenkins war versions, from updates.jenkins-ci.org
      --dist: Copy files from project to local script bin
      --dryrun|--dry-run: Just show expected source and destinations

      Jenkin in Docker:
      --up: start in docker container
      --down: bring down docker container
      --clean: stop dockler container & delete docker iamge
      --ssh: SSH into container
      --logs: attach to docker container logs

      Backup & Restore jenkins_home:
      --backup: Backup Jenkins home directory
      --restore: Restore Jenkins directory
      --archives: View archive files


    Examples:
      WAR:
        ${PROGNAME} --start
        ${PROGNAME} --start --ver=2.114
        ${PROGNAME} --start --ver=2.114 --dryrun
        ${PROGNAME} --stop
        ${PROGNAME} --stop --dryrun

      Docker:
        ${PROGNAME} --up
        ${PROGNAME} --restart
        ${PROGNAME} --down
        ${PROGNAME} --clean
        ${PROGNAME} --logs

      Backup & Restore:
        ${PROGNAME} --backup
        ${PROGNAME} --backup --home=~/jenkins_home
        ${PROGNAME} --restore --file=20180405.tgz
        ${PROGNAME} --restore --home=~/jenkins_home --file=20180405.tgz

      Helpers:
        ${PROGNAME} --latest
        ${PROGNAME} --archives
        ${PROGNAME} --versions

      Distribute (move files to script bin):
        ${PROGNAME} --dist

EOF
)

# files & directories
declare -r SCRIPT_DIR="$( dirname ${0} )"
declare -r CONFIG_FILE="${SCRIPT_DIR}/janks.conf.sh"

# actions
declare -i GET_LATEST=${FALSE}
declare -i BACKUP=${FALSE}
declare -i RESTORE=${FALSE}
declare -i START=${FALSE}
declare -i STOP=${FALSE}
declare -i ARCHIVES=${FALSE}
declare -i VERSIONS=${FALSE}
declare -i DISTRIBUTE=${FALSE}
declare -i DOCKER_UP=${FALSE}
declare -i DOCKER_RESTART=${FALSE}
declare -i DOCKER_LOGS=${FALSE}
declare -i DOCKER_DOWN=${FALSE}
declare -i DOCKER_CLEAN=${FALSE}
declare -i DOCKER_SSH=${FALSE}

# flags
declare -i DRYRUN=${FALSE}

# global variables
declare FILENAME=''
declare HOME_DIR=''
declare VERSION_TO_RUN=''
declare -a LOCAL_VERSIONS=()
declare -a REMOTE_VERSIONS=()
declare -a REQUIRED_VERSIONS=()

# ---------------------------------------
# COMMON FUNCTIONS
# ---------------------------------------
usage() {
  echo "${SYNTAX}"
}

error() {
  printf "\n%s\n" "Error: ${1}"
}

die() {
  error "${1}"
  usage
  printf "\n\n"
  exit "${2:-1}"
}

show_help() {
  printf "\n\n"
  usage
  printf "\n\n"
  exit 0
}

# ---------------------------------------
# MAIN CODE GOES HERE
# ---------------------------------------
source "${CONFIG_FILE}" \
  || die "Unable to load config: ${CONFIG_FILE}" 1

__check_home() {
  # check if jenkins home directory was specified
  # create it if required
  if [[ -n ${HOME_DIR} ]]; then
    JENKINS_HOME_DIR="${HOME_DIR}"
  else
    echo "Jenkins home directory was not supplied";
    echo "Default will be used: ${JENKINS_HOME_DIR}";
  fi

  [[ -d ${JENKINS_HOME_DIR} ]] \
    || mkdir -p "${JENKINS_HOME_DIR}"
}

__backup() {
  local datetime=$(date +%Y%m%d)
  local filename="${datetime}.tgz"
  local archive_file="${ARCHIVE_DIR}/${filename}"

  __check_home

  [[ -d ${ARCHIVE_DIR} ]] \
    || mkdir -p "${ARCHIVE_DIR}"

  if (( DRYRUN )); then
    echo
    echo "Back up Jenkins home directory"
    echo "From: ${JENKINS_HOME_DIR}"
    echo "To: ${archive_file}"
    echo
  else
    cd "${JENKINS_HOME_DIR}"

    tar -czf "${archive_file}" . &>/dev/null \
      && printf "\n🍄  Backed Jenkins up to:\n\t%s\n\n" "${archive_file}" \
      || printf "\n☠️  Failed to back up Jenkins to:\n\t%s\n\n" "${archive_file}"
  fi
}

__restore() {
  local dest_dir
  local archive_file
  [[ -z ${FILENAME} ]] \
    && die "No archive file was specified, use --file=<filename>" 3

  archive_file="${ARCHIVE_DIR}/${FILENAME}"

  __check_home

  # check if the file is there
  [[ -f "${archive_file}" ]] \
    || die "☠️  Unable to find archive: ${archive_file}" 2

  if (( DRYRUN )); then
    echo
    echo "Restore Jenkins home directory"
    echo "From: ${archive_file}"
    echo "To: ${JENKINS_HOME_DIR}"
    echo
  else
    tar -xzf "${archive_file}" -C "${JENKINS_HOME_DIR}" \
      && printf "\n🍄  Restored Jenkins to:\n\t%s\n\n" "${JENKINS_HOME_DIR}" \
      || printf "\n☠️  Failed to restore Jenkins from:\n\t%s\n\n" "${archive_file}"
  fi
}

__view_archives() {
  printf "\n💿  Jenkins home archives:\n"
  find "${ARCHIVE_DIR}" -type f -name *.tgz -exec sh -c 'echo $(basename {})' \;
  printf "\n"
}

__view_versions() {
  printf "\n📦  Jenkins local war versions:\n"
  find "${JENKINS_WAR_BASE_DIR}" -type d -exec sh -c 'echo $(basename {}) | grep -v war-files' \;
  printf "\n"
}

__get_local_versions() {
  LOCAL_VERSIONS=($(find "${JENKINS_WAR_BASE_DIR}" -type d -exec sh -c 'echo $(basename {}) | grep -v war-files' \;))
}

__get_remote_versions() {
  local -r url=https://updates.jenkins-ci.org/download/war/

  REMOTE_VERSIONS=($(curl "${url}" 2> /dev/null \
    | sed '/^\/ >/d' \
    | sed 's/<[^>]*.//g' \
    | egrep ^[0-9]+ ))
}

__get_required_versions() {

  local -a latest=()
  local ver
  local -a required_versions=()
  local -i found=${FALSE}
  # initialize required versions
  REQUIRED_VERSIONS=()

  __get_local_versions
  __get_remote_versions
  # trim down, only most 6 recent versions
  remote_versions=("${REMOTE_VERSIONS[@]:0:5}")
  # determine missiing versions
  for r in "${remote_versions[@]}"; do
    skip=
    for l in "${LOCAL_VERSIONS[@]}"; do
      [[ $r == $l ]] && { skip=1; break; }
    done
    [[ -n $skip ]] || REQUIRED_VERSIONS+=("$r")
  done

  # a little sanity checking
  echo "Local Versions: ${LOCAL_VERSIONS[@]}"
  echo "Remote Versions: ${remote_versions[@]}"
  echo "Required Versions: ${REQUIRED_VERSIONS[@]}"
}

__get_latest_versions() {
  local -r baseUrl=https://updates.jenkins-ci.org/download/war/
  local url
  __get_required_versions

  for ver in "${REQUIRED_VERSIONS[@]}"; do
    local dir="${JENKINS_WAR_BASE_DIR}/${ver}"
    local path="${dir}/jenkins.war"
    local url="${baseUrl}/${ver}"
    printf "👉🏻  Fetching version: %s\n" "${ver}"
    mkdir -p "${dir}"

    #curl --output "${path}" "${url}" \
    wget "${url}" -O "${path}" \
      && printf "👌🏻  Sucessfully downloaded version %s\n" "${ver}" \
      || printf "☠️  Failed to download version %s\n" "${ver}"
  done
}

__choose_version() {
  # choose jenkins version from available war files
  #local vers=($(find "${JENKINS_WAR_BASE_DIR}" -type d -exec sh -c 'echo $(basename {}) | grep -v war-files' \;))
  __get_local_versions
  echo "${vers[@]}"
  PS3="Select version to start: "
  select ver in "${LOCAL_VERSIONS[@]}" "Abort"; do
    if [[  $ver = "Abort" ]]; then
      exit 0
    else
      # pull the key from the value
      JENKINS_VER=${ver}
      return
    fi
  done
}

__start_menu() {
  __choose_version

  (( DRYRUN )) \
    && echo java -jar "${JENKINS_WAR_BASE_DIR}/${JENKINS_VER}/jenkins.war" \
    || java -jar "${JENKINS_WAR_BASE_DIR}/${JENKINS_VER}/jenkins.war" &

}

__start() {
  (( DRYRUN )) \
    && echo java -jar "${JENKINS_WAR_BASE_DIR}/${JENKINS_VER}/jenkins.war" \
    || java -jar "${JENKINS_WAR_BASE_DIR}/${JENKINS_VER}/jenkins.war" &
}

__stop() {
  if (( DRYRUN )); then
    ps aux | grep 'jenkins' | grep -v 'grep'
  else
    local -r pid=$(ps aux | grep jenkins | grep -v grep | awk '{print $2}')

    # TODO: get confirmation

    if [[ -z ${pid} ]]; then
      echo "🍒  No jenkins process is currently running"
    else
      kill "${pid}" \
        && echo "⚰️  Killed jenkins pid: ${pid}" \
        || echo "☠️  Unable to kill jenkins pid: ${pid}"
    fi
  fi
}

__distribute() {
  # move files into script bin
  echo "Distribute ${PROGNAME}"

  local file=''
  local -r dest=~/bin
  local -ra files=(
    "${PROGNAME}"
    "${CONFIG_FILE}"
  )
  printf "\n"
  for file in "${files[@]}"; do
    cp "${file}" "${dest}" \
      && printf "👍🏻  Copied: %s to %s\n" "${file}" "${dest}"
  done
  printf "\n"
}

__open() {
  open "http://127.0.0.0:8080"
}


__get_opts() {
  while (( $# > 0 )); do
    local arg="${1}"; shift;
    case ${arg} in
      --help)    show_help                ;;
      --backup)           BACKUP=${TRUE}  ;;
      --restore)         RESTORE=${TRUE}  ;;
      --start)            START=${TRUE}   ;;
      --stop)             STOP=${TRUE}    ;;
      --open)
        __open; exit 0;
        ;;
      --versions)        VERSIONS=${TRUE} ;;
      --archives)        ARCHIVES=${TRUE} ;;
      --dry-run|--dryrun) DRYRUN=${TRUE}  ;;
      --dist)         DISTRIBUTE=${TRUE}  ;;
      --ver*)
        [[ ${arg} =~ '=' ]] && JENKINS_VER="${arg#*=}"
        ;;
      --home*)
        [[ ${arg} =~ '=' ]] && HOME_DIR="${arg#*=}"
        ;;
      --file*)
        [[ ${arg} =~ '=' ]] && FILENAME="${arg#*=}"
        ;;
      --latest) # debug get latest wars
        GET_LATEST=${TRUE}
        ;;
      --local-vers) # debug test
        __get_local_versions
        ;;
      --volume)
        __create_volume
        ;;
      --view)
        __view_volume
        ;;
      *) die "Unknown option: ${arg}" ;;
   esac
  done
  return 0
}

__dispatch() {
  (( GET_LATEST )) && __get_latest_versions
  (( BACKUP )) && __backup
  (( RESTORE )) && __restore
  (( START )) && __start_menu
  (( STOP )) && __stop
  (( DISTRIBUTE )) && __distribute
  (( ARCHIVES )) && __view_archives
  (( VERSIONS )) && __view_versions
  return 0
}

__main() {
  (( ${#} < MIN_ARG_COUNT )) && die "Expects at least ${MIN_ARG_COUNT} arguments" 1
  (( $# > 0 )) && __get_opts "$@"

  __dispatch

  return 0
}
(( ${#} > 0 )) && __main "${@}" || __main

:<<'RESOURCES'
Jenkins war files

RESOURCES
